# Your presentation title
title: It Takes a Village to Develop a Coder… Lessons from the Curve


remote_theme: autotraderuk/jekyll-revealjs@v2.2.2
plugins:
  - jekyll-remote-theme

# Your presentation description (optional)
description: A talk about what I learned supporting people who were learning to code at Autotrader

# Your name (optional)
author: Mark Crossfield

# The Reveal theme
reveal_theme: at.css

# The Reveal transition
reveal_transition: default

# Path to the used theme (defaults to the Reveal.js standard theme path)
reveal_theme_path: assets/css/

# Additional custom CSS paths
extra_css:
  - extra.css

# Custom CSS for highlighting (defaults to reveal.js/lib/css/zenburn.css)
highlight_style_sheet: 

# Embed Server-side speaker notes?
reveal_notes_server: false

# Additional reveal.js options
reveal_options:
  slideNumber: 'c/t'
  fragmentInURL: true

# Additional reveal.js dependencies
reveal_dependencies:

# Reveal.js subdirectory
reveal_path: reveal.js/

# mermaid.js diagram integration
mermaid_diagrams: true
mermaid_theme: dark # See https://mermaid-js.github.io/mermaid/#/theming?id=deployable-themes
# mermaid_version: 11.0.2

# Exclude directories and/or files from the conversion
exclude:
  - Gemfile*
  - LICENSE
  - README.md

# Don't change anything below
markdown: kramdown
highlighter: rouge
markdown_ext: ignoreme

